#!/usr/bin/env python3
import klib
import getpass
import argparse
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--email",help="")
    parser.add_argument("--password",help="")
    args = parser.parse_args()
    email = args.email
    password = args.password

    try:
        if not email:
            email = input('email > ')
        elif not password:
            password = getpass.getpass('password > ')

        password = input('password > ')
        pin = input("pin > ")
        name = input('name > ')
        user = klib.Kahoot(pin, name)
        user.authenticate(email, password)
        user.checkPin()
        user.startGame()
    except KeyboardInterrupt:
        print('EXITING...')
        exit()
